version: '3'
services:
  #--------------------------------Monitoramento Prometheus--------------------------------------
  ##prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  ##Cadvisor - Monitoramento com gráficos
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  #-------------------------------Aplicação-------------------------->
  ##Banco de Dados Relacional da Aplicação - MYSQL    
  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes: 
      - ./mysql-data:/var/lib/mysql
      - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf
    environment:
      MYSQL_ROOT_PASSWORD: K@bum!
      MYSQL_DATABASE: 'envio_mensagens'
  #Web server
  php:
    build: .
    image: php:7.3-rc-apache
    volumes:
    - ./web:/var/www/html
    - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf
    ports:
    - '80:80'
    links:
    - mysql    
  #Phpmyadmin 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 5555:80
    volumes: 
    - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf
    environment:
      - PMA_ARBITRARY=1
  #--------------------------------------Monitoramento Graylog---------------------->    
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:3
    networks:
      - graylog
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.3
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://40.84.187.192:9000/
    networks:
      - graylog
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
#----------------------------------Rede para comunicação das aplicações graylog--------------------->
networks:
  graylog:
    driver: bridge