scrape_configs:
    - job_name: cadvisor
      scrape_interval: 5s
      static_configs:
      - targets:
        - cadvisor:8080
    - job_name: 'node-exporter' 
      static_configs: 
      - targets: ['monitoring.guidanz.com:9100']